# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import db_api_pb2 as db__api__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in db_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KeyValueDbStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/db_api.KeyValueDb/Put',
                request_serializer=db__api__pb2.KeyValue.SerializeToString,
                response_deserializer=db__api__pb2.Response.FromString,
                _registered_method=True)
        self.Read = channel.unary_unary(
                '/db_api.KeyValueDb/Read',
                request_serializer=db__api__pb2.Key.SerializeToString,
                response_deserializer=db__api__pb2.Response.FromString,
                _registered_method=True)
        self.ReadKeyRange = channel.unary_unary(
                '/db_api.KeyValueDb/ReadKeyRange',
                request_serializer=db__api__pb2.KeyRange.SerializeToString,
                response_deserializer=db__api__pb2.ResponseList.FromString,
                _registered_method=True)
        self.BatchPut = channel.unary_unary(
                '/db_api.KeyValueDb/BatchPut',
                request_serializer=db__api__pb2.BatchKeyValue.SerializeToString,
                response_deserializer=db__api__pb2.ResponseList.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/db_api.KeyValueDb/Delete',
                request_serializer=db__api__pb2.Key.SerializeToString,
                response_deserializer=db__api__pb2.Response.FromString,
                _registered_method=True)


class KeyValueDbServicer:
    """Missing associated documentation comment in .proto file."""

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadKeyRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchPut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyValueDbServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=db__api__pb2.KeyValue.FromString,
                    response_serializer=db__api__pb2.Response.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=db__api__pb2.Key.FromString,
                    response_serializer=db__api__pb2.Response.SerializeToString,
            ),
            'ReadKeyRange': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadKeyRange,
                    request_deserializer=db__api__pb2.KeyRange.FromString,
                    response_serializer=db__api__pb2.ResponseList.SerializeToString,
            ),
            'BatchPut': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchPut,
                    request_deserializer=db__api__pb2.BatchKeyValue.FromString,
                    response_serializer=db__api__pb2.ResponseList.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=db__api__pb2.Key.FromString,
                    response_serializer=db__api__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'db_api.KeyValueDb', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('db_api.KeyValueDb', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KeyValueDb:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/db_api.KeyValueDb/Put',
            db__api__pb2.KeyValue.SerializeToString,
            db__api__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/db_api.KeyValueDb/Read',
            db__api__pb2.Key.SerializeToString,
            db__api__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadKeyRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/db_api.KeyValueDb/ReadKeyRange',
            db__api__pb2.KeyRange.SerializeToString,
            db__api__pb2.ResponseList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchPut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/db_api.KeyValueDb/BatchPut',
            db__api__pb2.BatchKeyValue.SerializeToString,
            db__api__pb2.ResponseList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/db_api.KeyValueDb/Delete',
            db__api__pb2.Key.SerializeToString,
            db__api__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
