# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: db_api.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'db_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x62_api.proto\x12\x06\x64\x62_api\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\t\")\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t\"3\n\x0cResponseList\x12#\n\tresponses\x18\x01 \x03(\x0b\x32\x10.db_api.Response\".\n\x08KeyRange\x12\x11\n\tstart_key\x18\x01 \x01(\t\x12\x0f\n\x07\x65nd_key\x18\x02 \x01(\t\"0\n\rBatchKeyValue\x12\x1f\n\x05items\x18\x01 \x03(\x0b\x32\x10.db_api.KeyValue2\xf8\x01\n\nKeyValueDb\x12)\n\x03Put\x12\x10.db_api.KeyValue\x1a\x10.db_api.Response\x12%\n\x04Read\x12\x0b.db_api.Key\x1a\x10.db_api.Response\x12\x36\n\x0cReadKeyRange\x12\x10.db_api.KeyRange\x1a\x14.db_api.ResponseList\x12\x37\n\x08\x42\x61tchPut\x12\x15.db_api.BatchKeyValue\x1a\x14.db_api.ResponseList\x12\'\n\x06\x44\x65lete\x12\x0b.db_api.Key\x1a\x10.db_api.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'db_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEYVALUE']._serialized_start=24
  _globals['_KEYVALUE']._serialized_end=62
  _globals['_KEY']._serialized_start=64
  _globals['_KEY']._serialized_end=82
  _globals['_RESPONSE']._serialized_start=84
  _globals['_RESPONSE']._serialized_end=125
  _globals['_RESPONSELIST']._serialized_start=127
  _globals['_RESPONSELIST']._serialized_end=178
  _globals['_KEYRANGE']._serialized_start=180
  _globals['_KEYRANGE']._serialized_end=226
  _globals['_BATCHKEYVALUE']._serialized_start=228
  _globals['_BATCHKEYVALUE']._serialized_end=276
  _globals['_KEYVALUEDB']._serialized_start=279
  _globals['_KEYVALUEDB']._serialized_end=527
# @@protoc_insertion_point(module_scope)
